services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=social_players.settings
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - staticfiles:/app/staticfiles
      - ./media:/app/media

volumes:
  staticfiles:
